### ISSUE TITLE
Add Query parameters

### ISSUE THREAD

**Issue by firminochangani** [nextbss/proxypay#9]
I there, I also built and [API wrapper](https://github.com/flowck/proxypay-api) for ProxyPay using Nodejs and your repository helped me, thanks.

Would be nice if you add query parameters in get_references and get_payments methods just like the official API supports. 

Great project by the way. 

Best regards, Firmino.

**Comment by smaziano** [comment]
Hello Firmino,
Good to know that it helped you... and you welcome btw.
This gem was created to solve a very specific problem... but... for sure I'll add it asap.

**Comment by firminochangani** [comment]
Oh would be nice.

**Comment by smaziano** [comment]
It's a wrap... query parameters added for get_references and get_payments as per the version v0.2.0
